name: Run Python scripts

on: 
  workflow_dispatch
 

env:
  API_TOKEN: ${{ secrets.API_TOKENS}}
jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
     
        # Commonly enabled options, see https://github.com/actions/dependency-review-action#configuration-options for all available options.
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

       
       
        #   fail-on-severity: moderate
        #   deny-licenses: GPL-1.0-or-later, LGPL-2.0-or-later
        #   retry-on-snapshot-warnings: true
