name: Streamlit App Deployment

on:
  push:
    branches:
      - amalpanwar-patch-1

jobs:
  build:
    runs-on: ubuntu-latest
   

    steps:
      
    - name: Checkout code
      uses: actions/checkout@v3
     
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Use Python 3.11
        
    - name: Clear Python pip cache
      run: pip cache purge 

    - name: Install dependencies
      run: |
        sudo apt-get install python3.11
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install distutils
        
        

    - name: Run Streamlit
      run: |
        streamlit run strmlit_app.py
